# Generated by Django 4.1.2 on 2023-02-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('cont_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('cont_name', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='')),
                ('cont_address', models.TextField(default='')),
                ('cont_image', models.ImageField(default='', upload_to='static/images/Content/')),
            ],
        ),
    ]
