# Generated by Django 4.1.2 on 2023-02-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(default='', max_length=50)),
                ('cat_desc', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='cont_date',
            field=models.DateTimeField(default=None),
        ),
    ]
