# Generated by Django 4.1.2 on 2023-02-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profileapp', '0003_contents_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='cont_email',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='contents',
            name='cont_phonenumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
